title: <p align="center"> Sachin Mahale </p>
logo: /assets/img/Screenshot 2023-11-03 094622.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/UPDATELINK/">LinkedIn</a> |
  <a href="https://github.com/sachinmahale">GitHub</a>
 
  <br>  
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  <br>
  </p>
